[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12"
regex = "1"
url = "2.2"
tokio = { version = "1", features = ["full"] }
email_address = "0.2.5"
